baseURL = 'https://T4EQ.github.io/'
languageCode = 'en-us'
title = 'T4EQ - Tech For Equality'
theme = 'ananke'

SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
Paginate = 2

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
body_classes = "avenir bg-near-white"
fontWeight = "normal"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
# background_color_class = "bg-dark-blue "
recent_posts_number = 1
heading_font = "serif"