baseURL = 'https://t4eq.org/'
languageCode = 'en-us'
title = 'T4EQ – Tech for Equality'
theme = 'ananke'

SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = true
Paginate = 2

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = "black"
author = ""
favicon = ""
site_logo = "/images/logo/2026-03-26_T4EQ_Logo-Screen-negative.png"
description = "The last theme you'll ever need. Maybe."
body_classes = "avenir bg-near-white"
fontWeight = "normal"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
# background_color_class = "bg-dark-blue "
recent_posts_number = 1
heading_font = "serif"
canonicalURL = 'https://t4eq.org/'
custom_css = ["ananke/css/custom.css"]