name: Deploy to Gihub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          lfs: true
      - name: Install Nix
        uses: cachix/install-nix-action@v17
      - name: Build site
        run: nix build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
